### ISSUE TITLE
`EpubNavigatorFragment.PaginationListener.onPageChanged` no longer ever called

### ISSUE THREAD

**Issue by jerome65536** [readium/kotlin-toolkit#93]
### What happened?

The `EpubNavigatorFragment.PaginationListener.onPageChanged` callback is no longer ever called. It used to work, so I assume something changed in Readium. Still works in Swift.

The internal `EpubNavigatorFragment.WebViewListener.onPageChanged` does get called, which then fails to call `paginationListener.onPageChanged(pageIndex - 1, totalPages, locator)`, because
```kt
                val positions = publication.positionsByResource[resource.href]?.takeIf { it.isNotEmpty() }
                    ?: return
```
returns, since `publication.positionsByResource` is empty.

### Expected behavior

The `onPageChanged` should be called.

### How to reproduce?

1. Open any book without `application/vnd.readium.position-list+json` in the manifest.json.
2. Go to any page.
3. Missing callback.

### Environment

* Readium version: develop-SNAPSHOT, can't find a way of checking which version that really is, nor how to update the snapshot

#### Development environment

* OS: macos 10.15.7
* IDE: Android Studio 2021.1.1 Patch 2

**Comment by jerome65536** [comment]
Workaround — add an `onCreatePublication` parameter:
```kt
val publication = streamer.open(asset, allowUserInteraction = true, sender = application,
        onCreatePublication = {
            servicesBuilder.positionsServiceFactory = EpubPositionsService.createFactory()
        }
    )
    .getOrThrow()
```

However, doesn't seem to fix a missing `onPageChanged` when changing page via `go`.

**Comment by mickael-menu** [comment]
@jerome65536 Could you check out this PR and see if it fixes the issue? https://github.com/readium/kotlin-toolkit/pull/107

**Comment by jerome65536** [comment]
@mickael-menu Thanks, that seems to mostly help.

However, there's still a missing `onPageChanged` when changing page via `go` — in that case, there's only an `onPageLoaded`. Unless that's a feature, not a bug?

**Comment by mickael-menu** [comment]
I updated the PR and went for a different approach, now the `onPageChanged` event is sent every time the `currentLocator` changes.

**Comment by jerome65536** [comment]
Still not working in the test app when using one of our books such as:
[714311.webpub.zip](https://github.com/readium/kotlin-toolkit/files/8630835/714311.webpub.zip)

Note: Remove the `.zip` in the extension, had to add it to not get a Github error when trying to upload.
